### ISSUE TITLE
Resolve express-session errors on application startup

### ISSUE THREAD

**Issue by minademian** [joshuasorkin/vent-taskrouter#12]
The following shows up when you start up the application:

```node
Thu, 01 Sep 2022 21:15:08 GMT express-session deprecated undefined resave option; provide resave option at src/appInitializer.js:28:13
Thu, 01 Sep 2022 21:15:08 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at src/appInitializer.js:28:13
```

**Comment by joshuasorkin** [comment]
Express-session is being used for authentication, i think it's for maintaining user state as logged-in (for the web admin client). There's also a bunch of my homemade password management stuff. What if instead we just outsource our authentication to a SaaS like Firebase/OAuth/etc?

**Comment by minademian** [comment]
I agree, best to outsource to a library or a SAAS.
This would be out of scope though for the Docker PR, so will label this so that we refactor this later and update the title.

**Comment by minademian** [comment]
@joshuasorkin Is the web admin client part of v1/user testing? In other words, do we need to fix this?
If not, especially if the goal is that the web admin client moves to a React app, then we can remove this code altogether (including the web admin client) and close this issue.
Let me know what you think.

**Comment by joshuasorkin** [comment]
We don't need the web client for user test sessions--any realtime admin stuff can be handled through some combination of cli tools and Twilio console. Let's junk the web client and save it for the React front end.
