### ISSUE TITLE
Fix reference to command property in parameterCountMatch()

### ISSUE THREAD

**Issue by joshuasorkin** [joshuasorkin/vent-taskrouter#19]
In **sms.parameterCountMatch()**, there is a check to see if the "manual" command was entered, since "manual" is allowed to be submitted without parameters to just get a list of all commands.

We need to change the boolean check

`command.commandName == "manual"`

to

`command.name == "manual"`

or

`command.name === "manual"`

**Comment by minademian** [comment]
Resolved by #28
