### ISSUE TITLE
Need to check whether webhook URL defined at APP_BASE_URL exists

### ISSUE THREAD

**Issue by joshuasorkin** [joshuasorkin/vent-taskrouter#24]
I noticed that even if I don't have Ngrok running, all the startup operations defined in `app.listen` complete successfully, and it's not until I make a call or send a text to the Twilio number that the error shows up.  Before the webhook URLs are set via the `incomingPhoneNumbers` update, there should be a test to make sure that APP_BASE_URL returns 200 from POST.

**Comment by minademian** [comment]
Resolved by https://github.com/joshuasorkin/vent-taskrouter/pull/30
